#!/usr/bin/env python
# 08-2014 Manuel Moscoso Dominguez
# Vincular GUIAS a la BD
#
########## LIBRERIAS/PAQUETES ##########################################
#PARA CONECTAR A MYSQL
#PARA LOGS
#PARA SALIR
#PARA VERIFICAR EXISTENCIA DE ARCHIVO
#PARA RETARDO DE 20seg
########################################################################
import MySQLdb
import syslog
import sys
import os.path
from os import listdir
import time

########## VARIABLES CONEXION ##########################################


## FUNCION: main
## DESC: Funcion principal que permite la lectura del baston cada 1(s)
def main():
	servicio = True
	while servicio == True:
		
		syslog.syslog(syslog.LOG_INFO,"Integrador / %s" % str(time.time()))
		time.sleep(15)

if __name__ == "__main__":	
	main()
