

/*TABLA QUE REGISTRA INFORMACION SOBRE EL MONITOR*/
CREATE TABLE RFID_PARAMETROS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	PARAMETRO VARCHAR(20) NOT NULL,
	VALOR VARCHAR(20) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL,
	MODO VARCHAR(2) NOT NULL,
	PRIMARY KEY (ID)
);

/*TABLA QUE REGISTRA EL LOG DE LAS LECTURAS*/
CREATE TABLE RFID_LOG_DE_LECTURAS(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	FECHA DATETIME NOT NULL,
	FECHA_MONITOR DATETIME NOT NULL,
	BASTON VARCHAR(20) NOT NULL,
	RFID VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID)
);


/*TABLA QUE REGISTRA LAS LECTURAS*/
CREATE TABLE RFID_LECTURA(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	FECHA DATETIME NOT NULL,
	FECHA_MONITOR DATETIME NOT NULL,
	BASTON VARCHAR(20) NOT NULL,
	RFID VARCHAR(20) NOT NULL,
	ESTADO VARCHAR(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (ID)
);


/*TRIGGER QUE DELIMITA UN MAXIMO DE 2000 REGISTROS A LA TABLA RFID_LOG_DE_LECTURAS*/
DELIMITER $$
CREATE TRIGGER LOG_LECTURA
AFTER INSERT
ON RFID_LECTURA FOR EACH ROW
BEGIN
  SELECT COUNT(*) INTO @cnt FROM RFID_LOG_DE_LECTURAS;
  INSERT INTO RFID_LOG_DE_LECTURAS(FECHA,FECHA_MONITOR,BASTON,RFID) VALUES (NEW.FECHA,NEW.FECHA_MONITOR,NEW.BASTON,NEW.RFID);
  IF @cnt = 4000 THEN
    SELECT MIN(ID) INTO @id FROM RFID_LOG_DE_LECTURAS;
    DELETE FROM RFID_LOG_DE_LECTURAS WHERE ID = @id; 
  END IF;
END
$$
