########################################################################
# Manuel Moscoso Dominguez
# w3.Mobiquos.cl
# GPLv3
########################################################################
DIR_CONF=/etc/rfid_monitor/
check:
	echo " hola $USER  " 
	

